---
title: "Classifying heatwave events and calculating no. of days"
output: html_notebook
---

# Calculating heatwave days
load dependencies
```{r}
library(data.table)
library(tidyverse)
library(zoo)
```

read in data (and format accordingly)
```{r}
df <- fread('max_air_temp_csv_files/tasmax_rcp85_land-rcm_uk_12km_01_day_19951201-20001130.csv.gz')
```

restructure data
```{r}
# convert cols to rows for each day
df <- melt(df, id = c('projection_x_coordinate', 'projection_y_coordinate'))

# make NAs 0
df[is.na(df)] <- 0

df <- df %>% 
  # add a grid id for each pair of coordinates
  group_by(projection_x_coordinate,projection_y_coordinate) %>% 
  mutate(grid_id = cur_group_id()) %>% 
  ungroup() %>% 
  # add universal threshold to test
  mutate(hw_threshold = 24) %>% 
  rename(day_id = variable, temp = value) %>% 
  # ensure data is in chronological order by grid
  arrange(grid_id,day_id)
```


find where heatwave criteria is met
```{r}
df <- df %>% 
  # idenify whether the daily temperature meets or exceeds heatwave threshold
  mutate(above_threshold = if_else(temp >= hw_threshold, 1, 0)) %>% 
  # group by grid square and create a sum of the binary variable for the current day plus previous 2 days
  group_by(grid_id) %>% 
  mutate(roll = rollapplyr(above_threshold, 3, sum, partial = T)) %>% 
  ungroup() %>% 
  # where the sum is 3 (all three days meet or exceed heatwave threshold) assign 1, otherwise 0
  mutate(heatwave = if_else(roll == 3,1,0)) %>% 
  # remove intermediary columns
  select(-c(roll,above_threshold))
```

count number of heatwave days for each grid square (and time period?)
```{r}
heatwave_days <- df %>% 
  # group by grid square (and poss time period)
  group_by(grid_id) %>% 
  # sum heatwave days
  summarise(total = sum(heatwave))
```


