---
title: "Batch runs for one ensemble group"
output: html_notebook
---

# Calculating heatwave days
load dependencies
```{r}
library(data.table)
library(tidyverse)
library(zoo)
```

read in data (and format accordingly)
```{r}
# ammend these for each ensemble 
# 95-00 data
df1 <- fread('max_air_temp_csv_files/tasmax_rcp85_land-rcm_uk_12km_01_day_19951201-20001130.csv.gz')
# 25-30 data
df2 <- fread('max_air_temp_csv_files/tasmax_rcp85_land-rcm_uk_12km_01_day_20251201-20301130.csv.gz')
# 55-60 data
df3 <- fread('max_air_temp_csv_files/tasmax_rcp85_land-rcm_uk_12km_01_day_20551201-20601130.csv.gz')


lookup <- fread('lookup_table.csv')
```

restructure data
```{r}
# convert cols to rows for each day
df1 <- melt(df1, id = c('projection_x_coordinate', 'projection_y_coordinate')) %>% 
  mutate(period = '95-00')
df2 <- melt(df2, id = c('projection_x_coordinate', 'projection_y_coordinate')) %>% 
  mutate(period = '25-30')
df3 <- melt(df3, id = c('projection_x_coordinate', 'projection_y_coordinate')) %>% 
  mutate(period = '55-60')

df_all <- rbind(df1,df2,df3) %>% 
  mutate_at(vars(period), factor)

# make NAs 0
df_all[is.na(df_all)] <- 0

# merge threshold lookup
df_all <- left_join(df_all,lookup2)

df_all <- df_all %>% 
  # add a grid id for each pair of coordinates
  group_by(projection_x_coordinate,projection_y_coordinate) %>% 
  mutate(grid_id = cur_group_id()) %>% 
  ungroup() %>% 
  # rename variables
  rename(day_id = variable, temp = value) %>% 
  # ensure data is in chronological order by grid
  arrange(grid_id,day_id)
```


find where heatwave criteria is met
```{r}
df_all <- df_all %>% 
  # idenify whether the daily temperature meets or exceeds heatwave threshold
  mutate(above_threshold = if_else(temp >= hw_threshold, 1, 0)) %>% 
  # group by grid square and create a sum of the binary variable for the current day plus previous 2 days
  group_by(grid_id,period) %>% 
  mutate(roll = rollapplyr(above_threshold, 3, sum, partial = T)) %>% 
  ungroup() %>% 
  # where the sum is 3 (all three days meet or exceed heatwave threshold) assign 1, otherwise 0
  mutate(heatwave = if_else(roll == 3,1,0))
```

count number of heatwave days for each grid square (and time period?)
```{r}
heatwave_days <- df_all %>% 
  # group by grid square (and poss time period)
  group_by(grid_id,period) %>% 
  # sum heatwave days
  summarise(total_heatwave_days = sum(heatwave))

# find all unique combinations of coordinates and their corresponding grid ID
grid_lu <- unique(df_all[c(1,2,5)])

# add coordinates to the heatwave_days table
heatwave_days2 <- left_join(heatwave_days, grid_lu)[c(4,5,2,3)]

# !!!!!!!! amend name for each ensemble plot !!!!!!!!!!
fwrite(heatwave_days2, 'heatwave_days_ensemble1.csv')
```